# Generated by Django 2.2.11 on 2020-06-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('state_code', models.CharField(max_length=2)),
                ('property_Tax', models.FloatField()),
            ],
        ),
    ]
