# Generated by Django 2.2.11 on 2020-06-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertytax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytax',
            old_name='property_Tax',
            new_name='property_tax',
        ),
    ]
