# Generated by Django 2.2.11 on 2020-06-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('state_code', models.CharField(max_length=2)),
                ('tax_rate', models.FloatField()),
            ],
        ),
    ]
