# Generated by Django 2.2.11 on 2020-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcalculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrates',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
