# Generated by Django 2.2.11 on 2020-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcalculator', '0002_auto_20200612_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
